version: '3.8'

services:
  mongo:
    build:
      context: ./mongoDB
    image: database
    ports: 
      - "27017:27017"
    volumes: 
      - mongodb_data:/data/db
  nodejs:
    build:
      context: ./
    image: backend
    ports:
      - "5000:5000"
    env_file: 
      - ./nodejs.env
      - ./mongo.env
    depends_on:
      - mongo
volumes:
  mongodb_data: