apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: earora2/nodejs-app
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_HOST
              value: "mongodb-service.default"
            - name: MONGODB_PORT
              value: "27017"
            - name: NODEJS_PORT
              value: "5000"
